apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    name: my-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx

          
